core/src/CompletionStream.ts
core/src/Driver.ts
core/src/async.ts
core/src/types.ts
drivers/src/bedrock/index.ts
drivers/src/groq/index.ts
drivers/src/huggingface_ie.ts
drivers/src/mistral/index.ts
drivers/src/openai/index.ts
drivers/src/replicate.ts
drivers/src/test/TestErrorCompletionStream.ts
drivers/src/test/TestValidationErrorCompletionStream.ts
drivers/src/togetherai/index.ts
drivers/src/vertexai/index.ts
drivers/src/vertexai/models.ts
drivers/src/vertexai/models/gemini.ts
drivers/src/watsonx/index.ts
drivers/test/all-models.test.ts
drivers/test/assertions.ts

https://github.com/becomposable/studio/issues/17
This change effects a large number of files as the return type used to pass along stream chunks has changed from:
string (containing only the result chunk) ----> CompletionChunkObject 
Which supports: result, token_usage and finish_reason.
The below type has been introduced for utility functions so you can still use strings.
CompletionChunk = CompletionChunkObject | string
Old: character count
New: Reported token count or when streaming and nothing is reported, stream chunks are counted (treating each chunk as 1 token).
AWS models need to be checked, particularly Claude as the way the extra { is handled has changed.
In assertions.ts put a console.log(chunk) in the loop to output the whole object for each stream chunk. Similarly for …

Adds finish_reason and token_usage support, streaming included.

---

drivers/src/bedrock/index.ts
drivers/src/bedrock/payloads.ts
drivers/src/groq/index.ts
drivers/src/mistral/index.ts
drivers/src/mistral/types.ts
drivers/src/openai/index.ts
drivers/src/togetherai/index.ts
drivers/src/vertexai/models/gemini.ts
drivers/test/all-models.test.ts

https://github.com/becomposable/studio/issues/17
Supports:
- max_tokens
- stop_sequences
- top_k
- top_p
- presence_penalty
- frequency_penalty
as supported by the models/api/provider.
Also updates the test file to reflect this.
- OpenAI o1 models use the max_completion_tokens rather than max_tokens
- top_logprobs option currently ignored (commented out on supporting models) as it's output is not supported.
Use change in test file to set new options, try extreme values that are expected to be invalid, this confirms that the model/provider is reading the option correctly. Or large values that produce identifiable behaviour, i.e. lots of repetitions with -2.0 frequency_penalty.

Improves completion api with new input parameters for LLMs

---

drivers/src/togetherai/index.ts

Fixes an intermittent typescript build error by adding output type to getResponseFormat() in the TogetherAI driver.

fix: TogetherAI add output type to getResponseFormat()

---

core/src/formatters/nova.ts

Adds image support for inputs to Amazona Nova
* https://github.com/becomposable/llumiverse/issues/35
Supported file types are "jpeg" | "png" | "gif" | "webp"

feat35/ Add Image support to Amazon Nova

---

drivers/src/vertexai/models.ts

* https://github.com/becomposable/llumiverse/issues/48
Exposes the Gemini 1.5 002 version models, i.e. gemini-1.5-pro-002.
Also exposes the 001 versions similarly.
As a clean up, the embedding models are removed from the list. This does not make them inaccessible for embedding, it just mean you cannot use them for normal requests, which is correct.
AIModel listing names for 001 and 002 model version may change in future.

Feat48 - Gemini 1.5 version 002 models

---

.github/workflows/build-and-test.yml

Amazon Nova Canvas only exists on us-east-1, changing region to us-east-1 from us-west-2 for the vitest tests.

Fix: change vitest bedrock region to us-east-1

---

drivers/src/bedrock/index.ts
drivers/test/all-models.test.ts

Add generalised support for canStream, to support AWS cross-region inference
* https://github.com/becomposable/llumiverse/issues/37
AWS inference support is mostly automatic if the underlying model is supported. We were getting errors from the canStream function which used `getFoundationModel()` to check if the model string provided (which could be a model or inference profile) supports streaming.
This returned a error for inference profiles as you have to use `getInferenceProfile()` instead, and then `getFoundationModel()` on the underlying model. Similar was done for custom models.
The implementation only checks the first model in the inference profile. It is assumed all models have the same level of streaming support. For cross-region inference the models in the list should be the …

feat/37 Add generalised support for canStream, to support AWS cross-region inference

---

drivers/src/vertexai/models/gemini.ts

* https://github.com/vertesia/llumiverse/issues/53
As a temporary fix for the linked issue, I am removing ResponseSchema usage.
Schema support will still work, enabled through sending the schema as part of the prompt.
Some flags are also updated to be more correct to model support.
1.0 Ultra has forced JSON output disabled, everything else has it on.

Removes Gemini ResponseSchema usage.

---

drivers/src/vertexai/index.ts
drivers/src/vertexai/models.ts
drivers/src/vertexai/models/claude.ts
drivers/src/vertexai/models/gemini.ts
drivers/src/vertexai/models/imagen.ts
drivers/test/all-models.test.ts
drivers/test/image-gen.test.ts
package.json
pnpm-lock.yaml

Better model listing
Anthropic Claude support on VertexAI
Basic Imagen support

feat: Expanded Vertex AI support

---

drivers/src/bedrock/index.ts

* https://github.com/vertesia/llumiverse/issues/61
A bug with AWS Converse, is causing the max_tokens to be lowered from 8192, to 4096. See attached issue.
Changing the default value to accommodate.

Fix: Set default max_tokens value to 4096 for Claude 3.5 Sonnet

---

drivers/src/bedrock/index.ts

Amazon Nova Canvas currently uses the old Nova understanding models prompt format.
It was accidentally removed from using the appropriate formatter in:
* https://github.com/vertesia/llumiverse/pull/60
The converse format is inappropriate for Nova Canvas, and the converse api cannot be used for it.
Restores previous functionality for Amazon Nova Canvas
No functional change beyond that.

Restore Nova formatting for Amazon Nova Canvas

---

drivers/test/all-models.test.ts

llama-3.1-70b-versatile has been deprecated by groq.
Updating to  llama-3.3-70b-versatile in all-models.test.ts to pass the CI.
No functional change

Update llama-3.1-70b-versatile to llama-3.3-70b-versatile in groq test

---

drivers/src/vertexai/index.ts
drivers/src/vertexai/models/imagen.ts

* https://github.com/vertesia/llumiverse/issues/58
The text from prompts was being extracted incorrectly for Imagen.
Also separated prompt formatting entirely from Gemini. There is no change in behaviour as Gemini prompt formatting has been copy pasted but this ensures easier changes and more reliable behaviour in future.
Before:
After

Fix Imagen Prompt formatting

---

core/package.json
drivers/package.json
package.json
pnpm-lock.yaml

(Other changes are made by `pnpm` to sort the dependencies but the versions used for each dependency is not changed)

chore(deps): upgrade vitest to 2.1.9

---

core/src/formatters/openai.ts
drivers/package.json
drivers/src/openai/index.ts
drivers/src/xai/index.ts
drivers/test/all-models.test.ts
pnpm-lock.yaml

OpenAI support for various API options is patchy and not clearly or correctly documented.
See user made support matrix from 2 weeks ago:
https://community.openai.com/t/developer-role-not-accepted-for-o1-o1-mini-o3-mini/1110750/7
Picture for posterity:
Changes:
- Use `developer` role instead of `system` for **o1 (full)** and newer, i.e. **o3-mini**.
- Use `user` role instead of `system` for **o1-mini** and **o1-preview** which support neither `system` or `developer`.
- Align usage of tools for JSON support with model support
- Disable tools for **o1-mini** and **o1-preview**
- Add model specific options for testing (o1 model do not support temperature)
- Use `max_completion_tokens` instead of `max_tokens` for all models. This is equivalent for non-thinking models and needed for thinking …

Improve and fix OpenAI support for thinking models

---

core/src/Driver.ts
core/src/formatters/nova.ts
core/src/formatters/openai.ts
core/src/options/vertexai.ts
core/src/types.ts
drivers/src/bedrock/converse.ts
drivers/src/bedrock/nova-image-payload.ts
drivers/src/test/index.ts
drivers/src/vertexai/index.ts
drivers/src/vertexai/models/imagen.ts

* https://github.com/vertesia/llumiverse/issues/58
To be merged after: 
* https://github.com/vertesia/llumiverse/pull/76
as it includes that PR, but should be separated for clarity of purpose in the commit history.
Improves and adds to Imagen 3 support.
Fixes usage of imagen 3 model, to not be hardcoded to generate-001.
Adds support for Imagen capability, this includes "edit mode" the typical one shot generation and customization which is the "few shot" generation.
Fixes option display for Imagen models.

Feat imagen3 support

---

core/src/options/bedrock.ts
drivers/src/bedrock/index.ts

* https://github.com/vertesia/studio/issues/1193
Uses new generic model options support in Bedrock. 
As a consequence adds support for Claude 3.7 Extended Thinking mode.

Add specific model options for Bedrock

---

core/src/options/vertexai.ts
drivers/src/vertexai/models/imagen.ts

Refines the implementation of the customisation options, splitting it into 4 categories as per:
https://cloud.google.com/vertex-ai/generative-ai/docs/image/subject-customization
(see sidebar)
Also adds edit steps for the edit modes and cleans up some of the model options.

Imagen 3 Customisation Options

---

.renovaterc.json5

Adds a new group for model provider client libraries which we want to update frequently to make sure we are not developing to an old API.
Uses the bump strategy for said client libraries.

Update the renovate config json

---

drivers/package.json
drivers/src/vertexai/index.ts
pnpm-lock.yaml

google cloud ai platform 3.35.0 has brought "listAllVersions" support for the listing api.
This allows us to see older versions of models in the listing like Gemini 1.5 Pro 001.

feat: Vertex AI list all versions

---

drivers/src/bedrock/nova-image-payload.ts

* https://github.com/vertesia/studio/issues/1323
Originally added as part of the type control of model_options and because the image options are sufficiently unique that if we don't have the correct model options, we are unlikely to have overlap with other model options.
Removing as it has proven a unnecessary stop, turning small bugs into a full stop if the options_id is not correct.
This is in line with all other model which only log a warning.
Nova Canvas does and still will log a warning, so the issue can still be traced.

fix: Don't throw error for missing options_id for Nova canvas

---

drivers/test/all-models.test.ts

VertexAI and xAI were missing their console.warn for when the API key is not set and the tests are not run for those providers.

fix: adds test warning for vertexai and xAI if env is not set.

---

core/src/formatters/nova.ts
core/src/options/bedrock.ts
drivers/src/bedrock/nova-image-payload.ts

Adds basic inpainting and outpainting support to Amazon Nova Canvas 
and negative prompt support.

feat: Amazon Nova Canvas mask and negative support

---

.renovaterc.json5

Differing package manager versions across repos can cause subtle build issues in CI.
Separating them allows other dependency updates to go along unhindered and allows synchronising the update of package managers easier.

fix: separate package manager into own group

---

drivers/src/mistral/index.ts

Mistral embed has been returning zero, total tokens in the tests lately. Causing the test to fail.
This adds prompt and completion tokens as a fallback.
Looking at the output manually, we get something like:
usage: {
prompt_tokens: 3,
total_tokens: 0,
completion_tokens: 0,
request_count: null
}

fix: Mistral embed, use prompt and completion token as fallback

---

core/package.json
drivers/package.json
drivers/src/replicate.ts
examples/package.json
pnpm-lock.yaml

Upgrades eventsource to new major version. This package is only used in the replicate driver.

chore(deps): eventsource upgrade to v3

---

drivers/package.json
pnpm-lock.yaml

v4 of aiplatform is only a major version bump as they are upgrading to NodeJs 18.
This does not affect us, upgrading to v4 to get latest changes.
https://github.com/googleapis/google-cloud-node/releases/tag/aiplatform-v4.0.0

chore(deps): Upgrade google-cloud/aiplatform to v4

---

package.json
pnpm-lock.yaml

Updates to vite v6, we force version after 6.2.4 to avoid a security CVE impacting previous versions.

chore(deps): update vite to v6

---

.github/workflows/build-and-test.yml

Right now all the tests are being executed twice (once for the push event and the other for the pull_request event). Let's just keep one of them.

fix: remove duplicated event on pull_request

---

drivers/package.json
drivers/src/vertexai/index.ts
drivers/src/vertexai/models/gemini.ts
pnpm-lock.yaml

Recent changes together caused the build to fail:
https://github.com/vertesia/llumiverse/pull/107 - Update the npm package google-cloud/aiplatform to v4
https://github.com/vertesia/llumiverse/pull/111 - Used the authClient option when authenticating with aiplatform.
Due to a difference in underlying google-auth-library version between the aiplatform v4 (which uses 10.0.0 rc1) and all the other latest npm packages for google (which use 9.15.1) there is a type different between the version of authClient.
Reverting to the earlier aiplatform version fixes the build issue.
Applying the change in: https://github.com/vertesia/llumiverse/pull/111 
To similar ModelGarden client and using lazy initialisation to only begin authentication on first use, as we have a lot of clients in vertexai.
I also …

fix: Clean up VertexAI auth and downgrade to aiplatform 3.35.0

---

.renovaterc.json5

Some packages I added a @ when it was not needed.
Also adding @azure/identity to model client libraries.

fix: Update renovaterc.json5 to have correct package names

---

drivers/src/vertexai/index.ts

This fix is for VertexAI embeddings which uses the fetch client within the VertexAI driver. 
No other functionality is affected.
The authClient is a union type of JSONClient and GoogleAuth, JSONClient itself being a union type.
This meant .getAccessToken could either return a string directly or return a object of form { token: string ,...}. 
Then depending on how llumiverse was used, it would work in some cases and not others.
For example the tests were passed but elsewhere VertexAI embeddings became inaccessible due to the differing authClient.

fix: get Google Authentication access token for fetch client depending on type

---

drivers/src/watsonx/index.ts
drivers/src/watsonx/interfaces.ts

There was a typo in the watsonx driver, max_new_tokens was set to temperature.
This caused the execution to always fail when temperature was set to a decimal.
Typo has been fixed and extra model options have been added according to:
https://ibm.github.io/watsonx-ai-node-sdk/interfaces/0_1_x.WatsonXAI.TextGenRequestParameters-1.html

fix: watsonx model options corrected and expanded

---

drivers/test/all-models.test.ts

Updates the models used in the standard test to more recent alternatives.
Also fixes the bug with o1-mini, where stop_sequences are not supported.
This was working before so it may be that OpenAI changed their support. Or it never work, but previously did not give an error.

chore: update all models test

---

drivers/src/bedrock/index.ts

Filtering to only supported providers. This is the start of a change of approach to listModels, where listModels becomes a "whitelist" only showing supported models.
There is potential to support a show everything function in the future for diagnostics and ease of use.

feat: filter foundation models on AWS bedrock based on provider.

---

drivers/src/openai/index.ts
drivers/test/all-models.test.ts

Similar to : 
* https://github.com/vertesia/llumiverse/pull/118
However in this instance we are filtering using a word blacklist.
A whitelist is more ideal however there is no practical way to do this for openai.
On Azure, we can use the chat_completion filter to remove models more simply.
Azure docs: https://learn.microsoft.com/en-us/rest/api/azureopenai/models/list?view=rest-azureopenai-2024-10-21&tabs=HTTP#model
Azure has an issue where the specified models are not being used. The test was adjusted to account for this. Will revisit in a different PR.

feat: openai filter listing

---

drivers/src/openai/index.ts
drivers/test/tools.test.ts

Adds tool support for OpenAI models and moves the JSON formatting over to structured output.
Also adds conversation support.
Structured output is used implicitly when strict:true this include for the tools.
One of it's restrictions is that additionalProperties is not supported and must explicitly be set to false.
This can cause problems for "wildcard" objects that have no properties and just additionalProperties:true, in this instance the schema parser throws an error and we fallback on using strict:false.
In either case, defaults are not supported and are removed.

feat: OpenAI tools support and structured output for JSON support

---

drivers/src/bedrock/index.ts

The filtering was not working due to a case sensitivity issue and the details of the filter implementation that meant everything was being filtered.

fix: AWS Bedrock fix supported providers filtering

---

core/src/options/bedrock.ts
drivers/src/bedrock/index.ts

Adds support for the Writer models Palmyra X5 and X5 on AWS bedrock.
https://aws.amazon.com/about-aws/whats-new/2025/04/writers-palmyra-x5-x4-models-amazon-bedrock/

feat: AWS bedrock support for Writer Palmyra X5 and X4

---

core/src/index.ts
core/src/tools.ts
core/src/tools/bedrock.ts
drivers/src/bedrock/converse.ts
drivers/src/bedrock/index.ts
drivers/test/tools.test.ts

Implements tools support for AWS bedrock converse text execution.
Does not implement tool support for streaming.
Also implements a supportsToolUse function to query llumiverse if a model supports tools according to:
https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference-supported-models-features.html
We may modify the list, if problems arise with particular models. See Palmyra note.
Returns true, when supported.
Returns false, when known to be unsupported.
Returns undefined otherwise.
Noting, Palmyra does not work with tools at the moment, even though it lists it as supported. This is a Amazon-side issue, Palmyra is mistakenly returning the tool request in the text field.
Llama is noted to possibly require some changes in the AWS docs. These are worded as …

feat: AWS bedrock converse tools support

---

drivers/src/bedrock/converse.ts
drivers/src/bedrock/index.ts

The only thing stopping "incidental" support of Deepseek and previously Writer Palmyra models was the usage of '''json prefill. 
I am reversing the prefill logic, to not prefill by default, instead only for supported models.
This leaves some models in the if else stack with empty sections. Leaving in the empty sections for better clarity and self-documenting code.

feat: AWS deepseek support, reverse prefill logic

---

core/src/options.ts
drivers/src/bedrock/index.ts
drivers/src/bedrock/nova-image-payload.ts
drivers/src/vertexai/models/claude.ts
drivers/src/vertexai/models/imagen.ts

Moves model specific type exporting under options.ts, which allows them to be imported from llumiverse/core.
This fixes some build issues with using the relative path imports. (i.e. ../../../core/options/bedrock.js)

fix: model specific type imports under llumiverse/core

---

common/src/options/vertexai.ts
core/src/capability/vertexai.ts
drivers/src/vertexai/index.ts
drivers/src/vertexai/models.ts
drivers/src/vertexai/models/llama.ts
drivers/test/all-models.test.ts
pnpm-lock.yaml

Adds support for the new LLama MaaS (Models as a Service) API.
This adds support for LLama 4, 3.3, 3.2 and 3.1.
Not all models show up in the Listing API properly, so I've hardcoded them as a list.
Only text input and output support
Included models:
llama-4-maverick-17b-128e-instruct-maas
llama-4-scout-17b-16e-instruct-maas
llama-3.3-70b-instruct-maas
llama-3.2-90b-vision-instruct-maas
llama-3.1-405b-instruct-maas
llama-3.1-70b-instruct-maas
llama-3.1-8b-instruct-maas

feat: LLama MaaS support on VertexAI. LLama 4 and 3.

---

drivers/src/bedrock/converse.ts

There needs to be a tool response for every tool call, so empty responses are allowed.
This was mistakenly added as a defensive programming in
* https://github.com/vertesia/llumiverse/pull/171
The correct bug to fix there was to throw on a lack of ID, which is always needed.

fix: converse allow empty tool response

---

common/src/options/bedrock.ts
common/src/options/vertexai.ts
drivers/package.json
drivers/src/bedrock/index.ts
drivers/src/vertexai/models/claude.ts
pnpm-lock.yaml

Refactors the vertexai claude implementation for better code quality.
Handles the beta header output-128k-2025-02-19 for 128k output window.
Now allows visible thinking output, optionally. Off by default.
Includes support for redacted thinking blocks.

feat: VertexAI Claude refactor

---

core/src/stream.ts

In the utility function: readStreamAsUint8Array, we returned a buffer, because that is used to get the underlying data, and buffer extends Uint8Array so it passed typescript type checking.
However when using strict type checking (such as in external libraries), this will fail.
So we create a new Uint8Array object to return instead.

fix: use Uint8Array directly instead of buffer which extends it.

---

drivers/src/bedrock/index.ts
drivers/src/vertexai/models/claude.ts

We were having issues with the max_tokens taking up a large part of the context window.
Additionally, high quota usage and 100% failed runs because Claude 4 Sonnet on bedrock can go over the default quota with 1 run with maximum max_tokens.

fix: limit default Claude max_token to 16k when max_token is not provided.

---

core/src/CompletionStream.ts
core/src/Driver.ts

This allows better user feedback and debugging as it means the user can still get the final prompt processed by llumiverse even when the execution fails.

feat: add prompts to execution errors

---

drivers/src/vertexai/models/gemini.ts

Throw for all finish reasons other than:
stop,
max_tokens
unspecified
The initial impetus for this was "MALFORMED_FUNCTION_CALL" which means the model generation of the function call did not satisfy Google's parser, and thus trying to act on this function call is somewhat futile.
By throwing an error, dependant software can retry based on the error rather than checking for a model specific finish reason.

feat: VertexAI Gemini, throw if finish_reason is not allow listed

---

drivers/src/vertexai/index.ts
drivers/src/vertexai/models/imagen.ts

VertexAI Imagen and Anthropic were mistakenly using the project from the env file instead of the driver options.

fix: VertexAI Imagen and Anthropic use project from options

---

.github/workflows/build-and-test.yml
drivers/README.md

Many dependencies are dropping Node 18 support, we definitely do not support it.
Node 20, we are not using or testing it, better to just remove it.

chore: drop Node 18 and Node 20 support

---

drivers/src/bedrock/index.ts

Ensure that tool configuration is only added when the tool array is defined and not empty.

fix: bedrock only accepts non empty toolConfig array
