drivers/src/togetherai/index.ts
drivers/test/assertions.ts
drivers/test/togetherai/models.test.ts

use json mode if schema is present
test on llama2 and mixtral

add jsonmode with together ai

---

README.md
core/README.md
core/package.json
drivers/README.md
drivers/package.json

* https://github.com/becomposable/studio/issues/653

chore: change URL for llumiverse

---

README.md
core/README.md
drivers/README.md

Update workflow for build badge

Fix build badge

---

core/src/types.ts

[#987](https://github.com/vertesia/studio/issues/987)

fix: 987 - Remove output modality non supported type

---

drivers/package.json
package.json
pnpm-lock.yaml

Dependencies in the root folder, is inconsistent with the rest of the dependencies and caused issued for builds using this repo as a submodule.

Remove root dependencies

---

core/src/formatters/nova.ts
core/src/formatters/openai.ts
core/src/types.ts
drivers/src/bedrock/converse.ts
drivers/src/bedrock/nova-image-payload.ts

* https://github.com/vertesia/studio/issues/1314
Add common extra prompt roles for image generation.
This is a supporting PR and does not add functionality beyond adding the prompts and making sure they work in the existing system.

Add negative and mask prompts

---

core/src/options/vertexai.ts
drivers/package.json
drivers/src/vertexai/models/claude.ts
pnpm-lock.yaml

* https://github.com/vertesia/studio/issues/1193
Uses new generic model options support in VertexAI. 
Adds support for claude 3.7 thinking mode.

Add specific model options for Vertex AI

---

core/README.md
core/src/options.ts
core/src/options/groq.ts
drivers/README.md
drivers/package.json
drivers/src/groq/index.ts
pnpm-lock.yaml

Updates to latest groq sdk and adds model specific option support to Deepseek R1, no other models changed.
* https://github.com/vertesia/studio/issues/1193

Groq Partial Model Specific Option support

---

core/README.md
core/package.json
drivers/README.md
drivers/package.json
package.json
pnpm-lock.yaml

Upgrade to vitest 3.0.8 from 2.1.9
Upgrade applied in drivers, core and root.

chore(deps): upgrade vitest to 3.0.8

---

package.json

Upgrades from pnpm 9.15.2 to pnpm 10.6.2

chore(deps): use pnpm 10

---

drivers/src/vertexai/models/gemini.ts

Adds multiple function support to the existing tool implementation in Gemini.

feat: add multiple functions support for Gemini

---

drivers/src/vertexai/index.ts

~~Extracts model version information for Anthropic model on vertexai.~~
Removes duplicate models in the model listing.

fix: Remove duplicate model listing

---

drivers/package.json
drivers/src/replicate.ts
pnpm-lock.yaml

Replicate v1 has some breaking changes which don't affect us.
Small change to typing from any to unknown means in the code I cast back to any to maintain current code pattern.
Some code is questionable, noted with comment. Changing the implementation not in the scope of this PR.

chore(deps):Update replicate to v1

---

drivers/src/bedrock/converse.ts
drivers/src/bedrock/s3.ts

Converts amazonaws.com URL to s3 URI to use for Nova video understanding.

feat: Amazon Nova s3 bucket support for videos

---

drivers/src/vertexai/models/claude.ts

* https://github.com/vertesia/studio/issues/1734
Adds image and basic text document support to Anthropic Claude models on VertexAI

feat: vertexai claude image and text document support

---

drivers/src/openai/index.ts

* https://github.com/openai/openai-node/issues/1049#issuecomment-2362989934
One developer comment states that the API supports nullable.
We were getting an error
`model o4-mini: 400 Invalid schema for function ‘func’: In context=(‘a’, ‘b’, ‘c’, ‘d’, ‘e’), schema must have a ‘type’ key.`
Error was not present with older model. Fixed for o4-mini by not removing nullable and using null type.

fix: don't remove nullable and put nesting limit for OpenAI structured output

---

core/src/formatters/openai.ts
drivers/package.json
drivers/src/openai/azure.ts
drivers/src/openai/index.ts
pnpm-lock.yaml

Updates the Azure OpenAI API version in order to allow structured output on azure openai.
Also increases the list of models that do not support structured output, to allow them to work.

fix: update Azure openai version and expand list of not structured output supporting models.

---

drivers/src/bedrock/index.ts

Disable JSON prefill when using tools in bedrock.
JSON prefill can get in the way of tool execution, as it forces the model to continue the response from the prefill.

fix: Disable JSON prefill when using tools in bedrock

---

drivers/src/vertexai/index.ts

Improves the performance of vertexai listing which is quite close to network timeout on a cold start.
Still about 5-7 seconds on cold start.
2s when warm.
Removed a filter for Google response which was excluding some models unneccesarily like gemini flash-lite 2.5 and did not aid with performance.

feat: VertexAI parellel network requests for listing

---

drivers/package.json
drivers/src/vertexai/index.ts
pnpm-lock.yaml

AnthropicClient will make a GoogleAuthClient with local application default. Make it instead explicitly with the authClient.

fix: Explicitly make GoogleAuth with provided authClient
